<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('indexheader');
?>

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>WEBlogic Studio</b><br><small><b>Armored</b>Core v0.85</small><br>MVC Reference Framework</h1>
            <p class="tagline">Developing better Apps. Creating better professionals.</p>
            <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start') ?>">START NOW</a></p>
            <p class="small">By<i> Sílvio Priem Mendes, PhD</i></p>
        </div>
    </div>
</header>
<!-- /Header -->


<!-- Highlights - jumbotron -->
<div class="jumbotron top-space">
    <div class="container">
        <h3 class="text-center thin">Jogo do peixinho</h3>
        <div class="row">
            <div class="col-md-12 col-sm-12 highlight">
                
                Teste
            </div>
        </div> <!-- /row  -->

    </div>
</div>
<!-- /Highlights -->

<?php
Layout::includeLayout('footer')?>